-- Doctrine Migration File Generated on 2020-07-14 14:18:56

-- Version 20200714121704
CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, abstract LONGTEXT NOT NULL, wp1_title VARCHAR(255) DEFAULT NULL, wp1_desc VARCHAR(255) DEFAULT NULL, wp2_title VARCHAR(255) DEFAULT NULL, wp2_desc VARCHAR(255) DEFAULT NULL, wp3_title VARCHAR(255) DEFAULT NULL, wp3_desc VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE project (id INT AUTO_INCREMENT NOT NULL, gallery_id INT DEFAULT NULL, client_id INT DEFAULT NULL, image_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, start_date DATE DEFAULT NULL, finish_date DATE DEFAULT NULL, web_url VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_2FB3D0EE4E7AF8F (gallery_id), INDEX IDX_2FB3D0EE19EB6921 (client_id), UNIQUE INDEX UNIQ_2FB3D0EE3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE project_category (project_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_3B02921A166D1F9C (project_id), INDEX IDX_3B02921A12469DE2 (category_id), PRIMARY KEY(project_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE4E7AF8F FOREIGN KEY (gallery_id) REFERENCES media__gallery (id);
ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE19EB6921 FOREIGN KEY (client_id) REFERENCES client (id);
ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE3DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id);
ALTER TABLE project_category ADD CONSTRAINT FK_3B02921A166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE;
ALTER TABLE project_category ADD CONSTRAINT FK_3B02921A12469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE CASCADE;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200714121704', CURRENT_TIMESTAMP);
