# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    locales: ['en', 'es']
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Application,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.client:
        class: App\Admin\ClientAdmin
        arguments: [~, App\Entity\Client, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Clientes, label: Clientes, on_top: true }
        public: true

    admin.project:
        class: App\Admin\ProjectAdmin
        arguments: [~, App\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Proyectos, label: Proyectos, on_top: true }
        public: true

    admin.service:
        class: App\Admin\ServiceAdmin
        arguments: [~, App\Entity\Service, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Servicios, label: Servicios, on_top: true }
        public: true

    admin.privacy_policy:
        class: App\Admin\PrivacyPolicyAdmin
        arguments: [~, App\Entity\PrivacyPolicy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Política de Privacidad, label: Política de Privacidad, on_top: true }
        public: true

    admin.contact:
        class: App\Admin\ContactAdmin
        arguments: [~, App\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contactos, label: Contactos, on_top: true }
        public: true

    admin.newsletter:
        class: App\Admin\NewsletterAdmin
        arguments: [~, App\Entity\Newsletter, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Newsletter, label: Newsletter, on_top: true }
        public: true
